### ISSUE TITLE
Build failed without `--with-lz4-libdir`

### ISSUE THREAD

**Issue by haruue** [hsiangkao/erofs-utils#1]
I tried to build this project with:
```
$ ./autogen.sh
$ ./configure
$ make
```

and got following configure error:
```
checking for lz4.h... yes
checking for LZ4_compress_destSize in -llz4... no
configure: error: Cannot find proper lz4 version (>= 1.8.0)
```

I am sure that I have `lz4 1.9.2` installed, so I checked config.log and saw these link error:
```
configure:10419: checking for LZ4_compress_destSize in -llz4
configure:10444: gcc -o conftest -g -O2   -L  conftest.c -llz4   >&5
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

This error is caused by an empty `-L` flag in the gcc command. I looked into configure.ac and found:
https://github.com/hsiangkao/erofs-utils/blob/dd37a983616706414e2e4232e2aa96b56a09fed6/configure.ac#L177

When the `$with_lz4_libdir` is an empty string, `LDFLAGS=-L ${LDFLAGS}`, that's why we got the empty `-L`. 

Here is a working patch for dd37a983616706414e2e4232e2aa96b56a09fed6:

```patch
diff --git a/configure.ac b/configure.ac
index f925358..01a95e4 100644
--- a/configure.ac
+++ b/configure.ac
@@ -174,7 +174,7 @@ if test "x$enable_lz4" = "xyes"; then
 
   if test "x${have_lz4h}" = "xyes" ; then
     saved_LDFLAGS=${LDFLAGS}
-    LDFLAGS="-L$with_lz4_libdir ${LDFLAGS}"
+    LDFLAGS="-L$LZ4_LIBS ${LDFLAGS}"
     AC_CHECK_LIB(lz4, LZ4_compress_destSize, [
       have_lz4="yes"
       have_lz4hc="yes"
```

Please fix it.

**Comment by hsiangkao** [comment]
Hi Haruue,
Thanks for reporting this issue. 👍  :)
This github repo is only an internal working branch myself.
I rarely check the github issue list since the tradition for all linux kernel related projects is to post related stuffs to their mailing lists.

How about the following modification?
test -z "${with_lz4_libdir}" || LDFLAGS="-L$with_lz4_libdir ${LDFLAGS}"

If you have some time, could you send this patch to erofs mailing list so I can merge it directly?
use git send-email (or proper email client such as mutt) and erofs mailing list address is linux-erofs@lists.ozlabs.org

Or I will submit it for you.

Best regards,
Gao Xiang

**Comment by haruue** [comment]
`test -z "${with_lz4_libdir}" || LDFLAGS="-L$with_lz4_libdir ${LDFLAGS}"` should be a better idea. since $LZ4_LIBS would have a `-L` and an exter `-llz4` included.

Since I have sent this patch to linux-erofs@lists.ozlabs.org. I will close this issue now.

**Comment by hsiangkao** [comment]
Thanks, I have merged it to experimental branch, and I will move it to dev branch tomorrow.
