### ISSUE TITLE
big difference between squashfs and erofs size image

### ISSUE THREAD

**Issue by limbo127** [hsiangkao/erofs-utils#4]
Hello, 
I want to change squashfs to erofs image to performance issue, but my first test is very not exiting : 
/usr/local/bin/mkfs.erofs  -zlz4hc foo.erofs.img /run/WORK/CHROOT.NEW/
=>  foo.erofs.img = 553 Mo

mksquashfs /run/WORK/CHROOT.NEW/ tmp/chroot.sqfs  -noappend -comp lz4   -no-xattrs
=> /tmp/chroot.fs  = 290 Mo 

Erofs only compress image without any optimization found in squashfs ? 

Regards, 
Nicolas

**Comment by hsiangkao** [comment]
This is what as expected. Since EROFS uses 4kb fixed-sized output compression,
but squashfs uses 128kb fixed-sized input compression by default.

the comparable options are:
mksquashfs /run/WORK/CHROOT.NEW/ tmp/chroot.sqfs -b 4096 -noappend -comp lz4 -no-xattrs
mksquashfs /run/WORK/CHROOT.NEW/ tmp/chroot.sqfs -b 8192 -noappend -comp lz4 -no-xattrs

In principle, EROFS could support 128kb fixed-sized output compression in
the future as well, but for our current use scenario (Android smartphone),
128kb+4kb out of 4kb random I/O at once is not attractive, so I can only
say it's still on the wishlist.

**Comment by limbo127** [comment]
Ok,
thanks for your explanation
Regards,
Nicolas

Le lun. 21 sept. 2020 à 19:47, Gao Xiang <notifications@github.com> a
écrit :

**Comment by hsiangkao** [comment]
> Ok, thanks for your explanation Regards, Nicolas

Ok, I will close the issue.
